### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by g4s8** [g4s8/cactoos-cache#1]
Add `SoftBiFunc`, `SoftFunc`, `SoftScalar`, `SoftText` based on `SoftReference`.
Add `WeakFunc` based on `WeakReference`.

**Comment by g4s8** [comment]
@rultor hello

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#2](https://github.com/g4s8/cactoos-cache/issues/2), [#3](https://github.com/g4s8/cactoos-cache/issues/3), [#4](https://github.com/g4s8/cactoos-cache/issues/4) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#2](https://github.com/g4s8/cactoos-cache/issues/2), [#3](https://github.com/g4s8/cactoos-cache/issues/3) are still not solved; solved: [#4](https://github.com/g4s8/cactoos-cache/issues/4).
