### ISSUE TITLE
LRU caches

### ISSUE THREAD

**Issue by g4s8** [g4s8/cactoos-cache#5]
Add LRU cached `Func` and `BiFunc` implementations.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#7](https://github.com/g4s8/cactoos-cache/issues/7) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
done in d990106

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`
